name: Publish Bola Crate

on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: "Perform a dry run without actual publish"
        type: boolean
        default: false

  release:
    types: [published]
  push:
    tags:
      - "bola-v*" 

jobs:
  publish:
    name: Publish bola to crates.io
    runs-on: ubuntu-latest

    env:
      CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}

    steps:
      - name: 📦 Checkout repository
        uses: actions/checkout@v4

      - name: 🛠️ Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable

      - name: 🔍 Dry run (preview contents)
        if: github.event.inputs.dry_run == 'true' || (github.event_name != 'release' && github.event_name != 'push')
        run: cargo package --list -p bola

      - name: 🚀 Publish bola to crates.io
        if: (github.event_name == 'release' || github.event_name == 'push') || (github.event_name == 'workflow_dispatch' && github.event.inputs.dry_run != 'true')
        run: cargo publish -p bola